# Hexo Theme Murasaki

# ---------------------------------------------------------------
# Customization
# ---------------------------------------------------------------

# https://irocore.com/sumire-iro/
primary_color: "#7065a3"

favicon: /favicon.ico

# ---------------------------------------------------------------
# SEO Settings
# ---------------------------------------------------------------

# Set default keywords (Use a comma to separate).
keywords: "example, blog, hexo"

# Set a canonical link tag in your blog for SEO.
# See: https://support.google.com/webmasters/answer/139066
# Tips: Before you enable this, remember to set up your URL in
# hexo's _config.yml (e.g. `url: http://yourdomain.com`)
canonical: false

# ---------------------------------------------------------------
# Sidebar Settings
# ---------------------------------------------------------------

# Pages menu widget
menu_pages:
  archives:
    name: 归档
    path: /archives/
  about:
    name: 关于
    path: /about/

# Links menu widget.
# Put your social links or whatever you like here.
menu_links:
  github:
    name: GitHub
    path: https://github.com/example
  rss:
    name: RSS Feed
    path: /atom.xml

# ---------------------------------------------------------------
# Post Settings
# ---------------------------------------------------------------

# TODO: Under development
# Automatically excerpt. Not recommend.
# Please use <!-- more --> in the post to control excerpt accurately.
auto_excerpt:
  enable: false
  length: 150

# Table of content. Available values:
# - true: Enable TOC for all posts except ones specify `toc: false`.
# - false: Disable TOC.
toc: true

# Image Lazyload
lazyload:
  enable: true
  loading_image: images/loading.jpg

# ---------------------------------------------------------------
# Third Party Services
# ---------------------------------------------------------------

# DisqusJS - Render Disqus comments using API.
# See: https://github.com/SukkaW/DisqusJS
disqus:
  enable: false
  shortname:
  api:
  apikey:
  admin:
  admin_label:

# Google Analytics. For server-side ga,
# See: https://github.com/SukkaW/cloudflare-workers-async-google-analytics
google_analytics:
google_analytics_api:

# Google Search Console
google_site_verification:

# Google Font CDN (No trailing slash)
google_font: https://fonts.googleapis.com

# Post Views Counter
# Should implements: HTTP GET `${api}?pages=foo,bar,baz`
# which returns JSON in format: {"data": {"foo": 123, "bar": 456, "baz": 789}}
# See: https://github.com/printempw/google-analytics-hit-counter
post_views_counter:
  enable: false
  api:

# ---------------------------------------------------------------
# Miscelaneous
# ---------------------------------------------------------------

# Show a notice if the post hasn't been updated for more than 1 year.
# Customize the message in 'layout/_partials/post-warning.swig'.
expired_warning: false

# Resources for Open Graph meta tags.
# See: https://hexo.io/docs/helpers.html#open-graph
open_graph:
  # twitter_id:
  # twitter_site:
  # google_plus:
  # fb_admins:
  # fb_app_id:

# Script Vendors. Set a CDN address for the vendor you want to customize.
vendors:
  hancss: https://cdn.jsdelivr.net/npm/han-css@3.3.0/dist/han.min.css
  hancss_script: https://cdn.jsdelivr.net/npm/han-css@3.3.0/dist/han.min.js
  highlightjs: https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.16.2/build/highlight.min.js
  highlightjs_style: https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.16.2/build/styles/atom-one-light.min.css
  dayjs: https://cdn.jsdelivr.net/npm/dayjs@1.8.17/dayjs.min.js
  disqusjs: https://cdn.jsdelivr.net/npm/disqusjs@1.2.6/dist/disqus.js
  disqusjs_style: https://cdn.jsdelivr.net/npm/disqusjs@1.2.6/dist/disqusjs.css
  medium_zoom: https://cdn.jsdelivr.net/npm/medium-zoom@1.0.4/dist/medium-zoom.min.js
  vanilla_lazyload: https://cdn.jsdelivr.net/npm/vanilla-lazyload@12.4.0/dist/lazyload.min.js
  cfga: https://cdn.jsdelivr.net/npm/cfga@1.0.1/cfga.min.js
